stages:
  - build
  - deploy

build:dev:
  stage: build
  tags:
    - dev-server
  script:
    - sed -i "s|#CI_PID|$CI_PIPELINE_ID|g" VERSION
    - sed -i "s|#CI_HASH|$CI_COMMIT_SHORT_SHA|g" VERSION
    - sed -i "s|#CI_DATE|$(date -u +%d-%m-%Y)|g" VERSION
    - version=$(<VERSION)
    - sed -i "s|#XM_VERSION|$version|g" app/features/modal/modalVersion.js
    - sed -i "s|#XM_VERSION|$version|g" sw.js
    - npm install
    - yarn run build
    - rm -f README.md package-lock.json package.json package-lock.json webpack.common.js webpack.dev.js  webpack.prod.js yarn.lock 
    - rm -r node_modules
    - mkdir .dist
    - cp -r * .dist
    - mv .dist dist
  only:
    - dev
  artifacts:
    paths:
      - dist

deploy:dev:
  stage: deploy
  tags:
    - dev-server
  script:
    - sudo rm -rf /var/www/xm.iptp.dev/html/*
    - sudo cp -r dist/* $SITE_PATH_DEV
    - sudo chown -R www-data:www-data $SITE_PATH_DEV
  only:
    - dev
  dependencies:
    - build:dev

.buildprod:
  script: &buildprod
    - sed -i "s|#CI_PID|$CI_PIPELINE_ID|g" VERSION
    - sed -i "s|#CI_HASH|$CI_COMMIT_SHORT_SHA|g" VERSION
    - sed -i "s|#CI_DATE|$(date -u +%d-%m-%Y)|g" VERSION
    - version=$(<VERSION)
    - sed -i "s|#XM_VERSION|$version|g" app/features/modal/modalVersion.js
    - sed -i "s|#XM_VERSION|$version|g" sw.js
    - npm install
    - yarn run build:prod
    - rm -f README.md package-lock.json package.json package-lock.json webpack.common.js webpack.dev.js  webpack.prod.js yarn.lock 
    - rm -r node_modules
    - mkdir .dist
    - cp -r * .dist
    - mv .dist dist

.deployprod:
  script: &deployprod
    - sudo rm -rf /var/www/xm.iptp.net/html/*
    - sudo cp -r dist/* /var/www/xm.iptp.net/html
    - sudo chown -R nginx:nginx /var/www/xm.iptp.net/html

.blue-green-deploy:
  script: &blue-green-deploy
    - export DEPLOY_COLOR=$(if grep -q 'blue' /var/www/deployment_id; then echo 'green'; else echo 'blue'; fi;)
    - sudo ls /var/www/xm-$DEPLOY_COLOR/html/*
    - sudo cp -r dist/* /var/www/xm-$DEPLOY_COLOR/html
    - sudo chown -R nginx:nginx /var/www/xm-$DEPLOY_COLOR/html
    - sudo bash -c "echo $DEPLOY_COLOR > /var/www/deployment_id"

build:la:
  stage: build
  tags:
    - prod-la
  script:
   *blue-green-deploy
  only:
    - master
  artifacts:
    paths:
      - dist
    expire_in: 3 days

deploy:la:
  stage: deploy
  tags:
    - prod-la
  script:
    *blue-green-deploy
  only:
    - master
  dependencies:
    - build:la

build:ams:
  stage: build
  tags:
    - prod-ams
  script:
    *blue-green-deploy
  only:
    - master
  artifacts:
    paths:
      - dist
    expire_in: 3 days

deploy:ams:
  stage: deploy
  tags:
    - prod-ams
  script:
    *blue-green-deploy
  only:
    - master
  dependencies:
    - build:ams

build:sg:
  stage: build
  tags:
    - prod-sg
  script:
    *blue-green-deploy
  only:
    - master
  artifacts:
    paths:
      - dist
    expire_in: 3 days

deploy:sg:
  stage: deploy
  tags:
    - prod-sg
  script:
    *blue-green-deploy
  only:
    - master
  dependencies:
    - build:sg
